In [1]:
import pandas as pd

In [2]:
a=pd.read_csv('a.csv')
b=pd.read_csv('b.csv',header=None)

In [3]:
a.head()

           2017           2018                   2019                  2020
0  Aaron Sulema     Adi Lerner         Abraham Raanan  Amir Aharon Graitzer
1    Adam Toder    Adi Reisner             Adi Mahluf         Amit Toledano
2  Adi Abulafia    Adina Yogev  Ahi Refael Ido Lehrer         Anat Tzor Tal
3  Adi Ankonina     Alon Waitz   Ahuva Barzilay Gilad            Arie Maron
4    Adi Picker  Amir Ben Ezra         Alon Alfandari     Avi Loren Zafrani

In [4]:
b.head()

                0
0   Abraham Hanya
1  Adi Avramovich
2      Adi Mahluf
3      Adi Picker
4     Adi Reisner

In [5]:
liss = b[0].tolist()

In [6]:
print(liss)

['Abraham Hanya', 'Adi Avramovich', 'Adi Mahluf', 'Adi Picker', 'Adi Reisner', 'Adina Yogev', 'Adir Adler', 'Aharon Alcalay', 'Alexander Haik', 'Alon Peretz', 'Alon Salhov', 'Alon Salhov', 'Amit Ben Eliyahu', 'Amit Perry', 'Anastasia Cybelle Phillips', 'Anat Tzor Tal', 'Anat Yarkoni', 'Anat Yoffe', 'Arbel Cohen', 'Argaman Kadosh', 'Arie Larido', 'Ariel-Marco Pomrock', 'Arik Tarabulus', 'Asaf Benjamin', 'Asaf Gozali', 'Asaf Yosef Keidar', 'Assaf Yosef Kubi', 'Avi Keidar', 'Avi Sagi', 'Avi Sfadia-Shif', 'Avia Shashku', 'Aviad Hasson', 'Aviad Pinto', 'Avinoam Peretz', 'Aviram Avraham Sason', 'Avishai Azoulay', 'Avishay Aplaton', 'Aviv Perry', 'Aviv Tamar Ben Hamo', 'Aviva Margalit', 'Avner Erez\u200e\u200f', 'Avner Saban', 'Avraham Alon', 'Avraham Kalderon', 'Avraham Monsonego', 'Avraham Siddes', 'Ayelet Perl', 'Ayelet Zerach', 'Bar Ben Shahar', 'Bar Mazar', 'Barak Shem Tov', 'Barak Shem Tov', 'Batel Zaidman', 'Benny Moran', 'Benyamin Sarusi', 'Betty Goldfarb Silvera', 'Boaz Ben Bassat', 'Briana Barocas', 'Bruce Solomon', 'Camil Elram', 'Carmel Harel Goren', 'Carmela Yaari', 'Cary Math', 'Celia Maurice', 'Chaim Alon Demb', 'Chaim Alon Demb-2017', 'Chaim Lavi', 'Chana Mor', 'Chay Nahmiyas', 'Chen Mazal On', 'Dalit Ravon', 'Dan Paz', 'Dana Avraham', 'Dana Gamson', 'Dana Rina Vidergoren', 'Daniel Dayan', 'Daniel Eskapa', 'Daniel Prizmant', 'Danielle M Arama', 'Danny Mizrachi', 'Dave Gal', 'David Abu', 'David Elie Gholam', 'David Fransis', 'David Hamo', 'David Keres', 'David Mark Steinberg', 'David Peretz', 'Deganit Malal-Shahar', 'Dikla Hanan', 'Dina Givon', 'Dina Petel', 'Dina Senderov', 'Dina Yarkoni Levy', 'Dorit Spector', 'Doron Rabinian', 'Dror Azar', 'Dror Braunstein', 'Dror Ran Bar Lev', 'Dusty Dahan', 'Eden Shai London', 'Edith Schwartz', 'Efrat Babich Brit', 'Efrat Daniel Porat', 'Einat Carmel Ginzburg', 'Einat Hasson Bakai', 'Einav Bar', 'Eitan Eldar', 'Eitan Shalom Uzan', 'Eitan Ytzhak Nahum', 'Elana Bahat', 'Eldad Yair Ben Ezry', 'Eli Cohen Cohen', 'Eli Perez', 'Eliahu Garbi', 'Eliav Azulay Oz', 'Eliezer Ben Ezra', 'Eliran Sharon', 'Eliyahu Attais', 'Eliyahu Ofri', 'Ellen Esther Eskenazi', 'Eran Marc Kattash', 'Eran Pinhas Maman', 'Erez Bezalel', 'Erez Bilu', 'Erez Jonatan Goldberg', 'Erez Lenger', 'Eric Allan Leon', 'Ester-Hanna Medalsy', 'Eti Ester Chen Breier', 'Eyal Adanya', 'Eyal Ben-Ari', 'Eyal Dagan', 'Eyal Eli Ben Ami', 'Eyal Kugman', 'Eyal Netanel', 'Eyal Turjeman', 'Eytan Waldman', 'Gabriel Ronen Billu', 'Gady Elkarif', 'Gal Assraf', 'Gal Niv', 'Gal Rosilio', 'Galit Lior', 'Galit Noy', 'Ganit Shely Eliad', 'Gavriel Habib', 'Geva Alon', 'Gidon Veksler', 'Gil Or Shaul', 'Gil Yacov Telio', 'Gila Elhanany', 'Gila Regev', 'Gilad Hay Levi', 'Gilad Nae', 'Gili Friedman', 'Guri Avner Kalev', 'Guy Kagan', 'Guy Zagdon', 'Hadar Meshumar', 'Hadar Shoshan', 'Hagay Cole', 'Haim Shamir', 'Hanan Malul', 'Hen Firman', 'Hila Ben David', 'Hila Goldman', 'Hila Waldman Kotler', 'Howard Avi Capon', 'Howard Avi Capon', 'Idan Or', 'Idit Gawiser', 'Igal Gigi', 'Ilana Baruch', 'Ilit Eden Zohar', 'Inbal Levy', 'Inbal Marciano', 'Inbar Albalach', 'Iris Salomon Har-Even', 'Irit Kita', 'Isaac David Zhukovsky', 'Israel Adir', 'Israel Adir', 'Israel Adir', 'Ita Ester Dalya Deri', 'Itamar Dychtwald', 'Itamar Fitoussi', 'Itamar Hassin', 'Itay Shemesh', 'Itzhak Bar Siman Tov', 'Itzik Cohen', 'Izhak Gatenyo', 'Jack Joseph Amiel', 'Jacob Dali Levy', 'Jennifer Mesrie', 'Jessie Ben-Ami', 'Joseph Raz', 'Joshua Alexander Lever', 'Judi Naor', 'Judith Ann Melinek', 'Karen Abramovich Zion', 'Karyn Aleya Seroussi', 'Kathryn Harris', 'Katie Goldblatt', 'Keren Mazor-Javetz', 'Kobi Asaiag', 'Lidor Ohayon', 'Lilakh Dror Ben Menashe', 'Limor Oliva-Nahmias', 'Lior Ben Tov', 'Lior Ziv', 'Liron Brinder', 'Liron Cohen', 'Liron Pilosof', 'Lyron Live Bentovim', 'Maanit Yehodit Shlezinger', 'Magen Levi', 'Mali Malka Abadi', 'Manor Nili', 'Mark Alan Borenstein', 'Matan Drori', 'Matan Drori', 'Matan Gadi Pitohovski', 'Maurice Kaspy', 'Maximilian Barret Reiff', 'May Elgrabli', 'Maya Koren', 'Maya Koren Widder', 'Maya Kuperberg', 'Mayan Angel', 'Meir Amarin', 'Meir Elmekies', 'Meir Tangi', 'Meirav Adi Baron', 'Meital Porati Tsoref', 'Merav Askayo Moshe', 'Meyrav Aviv Goren', 'Michal Ariel Rotem', 'Michal Chaimov Shani', 'Michal Maduny', 'Michal Moyal', 'Michal Ruchman', 'Michal Schneider', 'Michal Segev', 'Michal Yahia', 'Michali Beeri', 'Michelle Beth Abarbanel', 'Miri Cohen', 'Miriam Tamam', 'Mor Avziz', 'Mor Azulay', 'Moran Ben Atar', 'Moran Cohen', 'Mordechai Mizrahi', 'Mordehai Yamin', 'Moren Dori', 'Mory Katan', 'Moshe Chen', 'Moshe David', 'Moshe Galina', 'Myrna Moshayov', 'Naama Lotan', 'Naftali Dery', 'Nahman Asulin', 'Nataly Sherf', 'Natan Kaduri', 'Nechama Ido', 'Netanel Nachmias Bashkin', 'Netta Gal', 'Nily Or Katz', 'Nina Linda Safdie', 'Nir Nisim Cohen Hershkovitz', 'Nir Shraga Tessler', 'Nisim Niso Gulzari', 'Nisim Shushan', 'Nissim Nino Romano', 'Nitsan Avioz', 'Niv Nisan Sfaradi', 'Noa Mashiach', 'Noa Musih', 'Noa Tsarfaty', 'Noah Peretz', 'Noam Bakal', 'Noam Hasson', 'Noam Mazor', 'Noam Nevo', 'Noam Paz', 'Nofar Esti Jano', 'Nofar Maoda', 'Nofar Zaban', 'Noy Shany', 'Noy Tiram', 'Nurit Kaminski', 'Ofer Amar', 'Ofer Ariel', 'Ofer Nissim', 'Ofer Yechzkel Zvi', 'Ofir Galimidi', 'Ofra Shelly', 'Ohad Bar Shimon', 'Ohad Vahaba', 'Ohad Zmirin', 'Omer Gaiero', 'Omer Moysa', 'Omer Segev', 'Omri Buchbinder', 'Omri Kadosh', 'Omri Russo', 'Oni Maman Kornblit', 'Or Asaf', 'Or Dov Asaf', 'Or Lankry', 'Or Tores', 'Or Yaacov', 'Orel Bitan', 'Oren Almog', 'Oren Kadosh', 'Ori Cohen', 'Ori Kerem', 'Ori Laor', 'Ori Laufer Laor', 'Ori Moshe Demb Wife', 'Orit Hod', 'Orit Vayns', 'Orly Bukchin', 'Orly Pariente Cohen', 'Orly Sol Levy', 'Orna Ariela Lavi', 'Orna Ashkenazi', 'Orna Hertzog', 'Orna Ravid', 'Ortal Afriat', 'Oryan Sheetrit', 'Osnat Azarzar', 'otam Yankovitch', 'Ovadia Rapaport', 'Philippa Jane Hyam', 'Pnina Ben-Shlomo', 'Rachel Greenberg', 'Racheli Sonego', 'Rahel Shemer', 'Rami Shmueli', 'Ran David Dahan', 'Ran Sharon', 'Ran Shimoni', 'Refael Neria Lasry', 'Reut Assor Zonens', 'Revital Tahan', 'Robin Vicki Gilman-Capon', 'Ron Gagin', 'Ron Gispan', 'Ron Mekler', 'Ronen Aharfi', 'Ronen Levi', 'Ronen Skapa', 'Roni Angel', 'Ronit Davidovitch', 'Roy Hittin Messiah', 'Russell John Harris', 'Sagi Alagem', 'Samuel Falkon', 'Sara Leizrovitz', 'Sara Levman', 'Sara Portnoy', 'Shabtai Eliezer Hackman', 'Shachar Peretz', 'Shahar Azarzar', 'Shahar Galizki', 'Shahar Harus', 'Shahar Segev', 'Shahar Shimon Abergel', 'Shahar Yosef Nabat', 'Shai Liran', 'Shai Mazor', 'Shai Ron Hareli', 'Shai Ron Lazarovitch', 'Shai Schwarzwald', 'Shai Vakrat', 'Shani Sabag', 'Sharon Ben David', 'Shaul Stavi', 'Shay Dvir', 'Shay Raz', 'Shay Shalom Shasha', 'Shay Shmaya Carmel', 'Shimon Filo', 'Shimon Hadad', 'Shimon Ohana', 'Shimon Tal', 'Shir Cohen', 'Shir Ester Dan', 'Shira Shmuel', 'Shlomi Nahumson', 'Shlomi Zohar', 'Shlomit Kafri', 'Shlomo Bueno', 'Shlomo Hay Amar', 'Shlomo Markus', 'Shlomo Sarfati', 'Shmuel Tachan', 'Shmuel Yakir Pereg', 'Shoshana Biton', 'Shoshana Gal', 'Sigal Tapuchi', 'Sigalit Keissar', 'Simha Samray', 'Sivan Sarusi', 'Sol Renato', 'Suf Krudo', 'Susan Joy Kacev', 'Tal Ben Zion', 'Tal Dam Ari', 'Tal Fruchter', 'Tal Maman', 'Tal Schwarz Shahar', 'Tal Vidergoren', 'Tali Levy', 'Tamar Amitay-Suchowolski', 'Tamar Azoulay', 'Tamar Edri', 'Tamar Shak', 'Timothy David Nathan', 'Tobias Oliver Sebastian Green', 'Tom Haimoff', 'Tom Noah', 'Tom Roseman', 'Tom Sonderousie', 'Tomer Sayag', 'Tzion Meir Maymon', 'Tzvi Kaplan', 'Uzi Yadid', 'Vered Gadash', 'Victor Osher Dahan', 'Yaacov Koby Ohayon', 'Yaakov Melloul', 'Yaakov Naaman', 'Yaar Erez', 'Yael Eldar', 'Yaelle Kalifon', 'Yair Gur', 'Yair Shalom Ifrach', 'Yaniv Blustein', 'Yaoz Friedman', 'Yarden Barak', 'Yaron Aharon Levi', 'Yaron Drikes', 'Yehezkel Yaacoby', 'Yehonatan Refael Bouskila', 'Yehuda Ashkenazi', 'Yigal Shoval', 'Yizhak Shmaya', 'Yizhak Zion', 'Yoav El-Kayam', 'Yogev Bouhadana', 'Yonatan Shlomo Ben Hai', 'Yonit Zaken', 'Yosef Bijaoui', 'Yosef Vanunu', 'Yosi Asaf Kahlon', 'Yotam Ben David', 'Yotam Yankovitch', 'Youval Harari', 'Yuhai Shimon Tal', 'Yuval Haft', 'Yuval Hogeg', 'Yuval Yoli Yitzhak', 'Yuval Yosef', 'Zehava Lazimi', 'Zehava Segal', 'Zion Doron Zanco', 'Ziva Katz', 'Zohar Gev', 'Zohar Shlomo Shriki', 'Zvi Yamin']

In [7]:
def conver(name):
    if name in liss:
        pass
    else:
        return name

In [8]:
a['2017'] = a['2017'].map(lambda x: conver(x))

In [9]:
a.head()

           2017           2018                   2019                  2020
0  Aaron Sulema     Adi Lerner         Abraham Raanan  Amir Aharon Graitzer
1    Adam Toder    Adi Reisner             Adi Mahluf         Amit Toledano
2  Adi Abulafia    Adina Yogev  Ahi Refael Ido Lehrer         Anat Tzor Tal
3  Adi Ankonina     Alon Waitz   Ahuva Barzilay Gilad            Arie Maron
4          None  Amir Ben Ezra         Alon Alfandari     Avi Loren Zafrani

In [10]:
a['2018'] = a['2018'].map(lambda x: conver(x))

In [11]:
a.head()

           2017           2018                   2019                  2020
0  Aaron Sulema     Adi Lerner         Abraham Raanan  Amir Aharon Graitzer
1    Adam Toder           None             Adi Mahluf         Amit Toledano
2  Adi Abulafia           None  Ahi Refael Ido Lehrer         Anat Tzor Tal
3  Adi Ankonina     Alon Waitz   Ahuva Barzilay Gilad            Arie Maron
4          None  Amir Ben Ezra         Alon Alfandari     Avi Loren Zafrani

In [12]:
a['2019'] = a['2019'].map(lambda x: conver(x))

In [13]:
a.head()

           2017           2018                   2019                  2020
0  Aaron Sulema     Adi Lerner         Abraham Raanan  Amir Aharon Graitzer
1    Adam Toder           None                   None         Amit Toledano
2  Adi Abulafia           None  Ahi Refael Ido Lehrer         Anat Tzor Tal
3  Adi Ankonina     Alon Waitz   Ahuva Barzilay Gilad            Arie Maron
4          None  Amir Ben Ezra         Alon Alfandari     Avi Loren Zafrani

In [14]:
a['2020'] = a['2020'].map(lambda x: conver(x))

In [15]:
a.head()

           2017           2018                   2019                  2020
0  Aaron Sulema     Adi Lerner         Abraham Raanan  Amir Aharon Graitzer
1    Adam Toder           None                   None         Amit Toledano
2  Adi Abulafia           None  Ahi Refael Ido Lehrer                  None
3  Adi Ankonina     Alon Waitz   Ahuva Barzilay Gilad            Arie Maron
4          None  Amir Ben Ezra         Alon Alfandari     Avi Loren Zafrani

In [18]:
a=a.dropna()

In [19]:
a

,2017,2018,2019,2020
0,Aaron Sulema,Adi Lerner,Abraham Raanan,Amir Aharon Graitzer
3,Adi Ankonina,Alon Waitz,Ahuva Barzilay Gilad,Arie Maron
7,Amit Cohen,Amit Miller,Amir Reuveni,Avraham Mazor
9,Amit Silvera,Amit Sella,Anat Goren,Danit Wainstok
10,Amnon Sintov,Amnon Cohen,Anat Zaid,Dor Elkayam
11,Anat Rubio,Anat Benish,Ariel Berli,Efraim-Amnon Damari
12,Arad Rubinovich,Anat Yona,Ariel Moshe Zohar,Ehud Canetti
14,Asaf Sidi,Asher Asaraf,Arik Isak,Eliran Tourjeman
17,Avishay Maya,Aviv Ben David,Aviv Farhi,Elor Levy
22,Avraham Shlomo Perl,Bosmat Cohen Twik,Bar Dror,Guy Gorenshten
23,Barak Akrish,Coral Dvora Hartman,Ben Zvi Yosef,Haim Dam Ari
24,Bella Boni,Dafna Mardix Katz,Bilha Billy Zouler,Idan Benyamin
26,Benyamin Dagan,Daniel Halifa,Dana Cohen,Itamar Yehuda Nehama
32,Dana Matarasso Anatot,Dina Shaim,David Huri,Michal Bardes
34,David Abutbul,Dor Yaakov Moshe Pazuelo,David Shotan,Michal Sharel
36,David Hayut,Dror Kantarovich,Dorit Guterman,Mordehai Agmon
37,David Kovas,Dror Moshe,Dror Tevet,Mory-El Mazal Ovadya
38,David Mellul,Ehud Rojanski,Efrat Ben Yehuda Levin,Nadav Olmert
39,David Monsonego,Elam Meir Friedlander,Ehud Dov Molcho,Nir Moshe Dagan
40,David Yair Prag,Eliyahu Lalush,Ehud Toucatly,Odelia Shuker
41,David Zalayet,Eliyahu Panaso,Eidit Adela Ben Aharon,Or Ben Harosh
43,Dor Ashkar,Elul Suchowolski,Elad Levi,Oren Gottesman
45,Doron Flohr,Etay Raz,Eldad Bouganim,Orli Shoval
49,Efrat Barak,Gil Shalom,Ella Amit,Rotem Amar
50,Ehud Moshe Levy,Gilad Bachar,Ella Goldshtein,Rotem Kuriel
51,Eilat Shavit,Gili Maimon,Emri Pariante,Roy Rosenblatt Nir
52,Einat Gdaliyahu,Golan Septon,Eran Ahadot,Segev Haviv
53,Einat Hasson-Bakai,Guila Tamir,Eran Ben Harosh,Shahar Shlomo Tsiper
55,Eli Avisris,Hadas Arazi,Eti Regev Oria,Shalom Ben Ezri
57,Eliahu Bitran,Haim Hasson,Eyal Leon,Shany Saray Naaman
58,Eliya Ovadia,Hila Talya,Freddy Busidan,Shir Blustien
64,Eyal Ozsinay,Ike Mor,Gavriel Surujon,Yaron Avidan
67,Gideon Dar,Isacc Hanuka,Gilad Wallach,Yogev Aviad Sembira Nahum

In [22]:
a.to_excel('a_final.xlsx')